/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiGeneratePhaseRouteImport } from './routes/api/generate-phase'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'

const ApiGeneratePhaseRoute = ApiGeneratePhaseRouteImport.update({
  id: '/api/generate-phase',
  path: '/api/generate-phase',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AuthenticatedAppRoute
  '/api/generate-phase': typeof ApiGeneratePhaseRoute
}
export interface FileRoutesByTo {
  '/app': typeof AuthenticatedAppRoute
  '/api/generate-phase': typeof ApiGeneratePhaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/api/generate-phase': typeof ApiGeneratePhaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/api/generate-phase'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/api/generate-phase'
  id: '__root__' | '/_authenticated/app' | '/api/generate-phase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  ApiGeneratePhaseRoute: typeof ApiGeneratePhaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/generate-phase': {
      id: '/api/generate-phase'
      path: '/api/generate-phase'
      fullPath: '/api/generate-phase'
      preLoaderRoute: typeof ApiGeneratePhaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  ApiGeneratePhaseRoute: ApiGeneratePhaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
